shop/main_app/urls.py
from django.urls import path
from .views import BaseView, ProductDetailView,  CategoryDetailView

urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('products/<str:ct_model>/<str:slug>', ProductDetailView.as_view(), name='product_detail'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/main_app/models.py
import sys
from io import BytesIO

from PIL import Image
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

User = get_user_model()


def get_models_for_count(*model_names):
    return [models.Count(model_name) for model_name in model_names]


class MinResolutionErrorException(Exception):
    pass


class MaxResolutionErrorException(Exception):
    pass


def get_product_url(obj, viewname, urlpattern_name, model_name):
    ct_model = obj.__class__meta.model_name
    return reverse(viewname, kwargs={'ct_model': ct_model, 'slug': obj.slug})


class LatestProductsManager:

    @staticmethod
    def get_products_for_main_page(*args, **kwargs):
        with_respect_to = kwargs.get('with_respect_to')
        products = []
        ct_models = ContentType.objects.filter(model__in=args)
        for ct_model in ct_models:
            model_products = ct_model.model_class()._base_manager.all().order_by('-id')[:5]
            products.extend((model_products))
        if with_respect_to:
            ct_model = ContentType.objects.filter(model=with_respect_to)
            if ct_model.exists():
                if with_respect_to in args:
                    return sorted(products,
                                  key=lambda x: x.__class__._meta.model_name.startwith(with_respect_to),
                                  reverse=True)
        return products


class LatestProducts:
    objects = LatestProductsManager()


class CategoryManager(models.Manager):

    CATEGORY_NAME_COUNT_NAME = {
        'Ноутбуки': 'notebook__count',
        'Смартфони': 'smartphone__count'
    }

    def get_queryset(self):
        return super().get_queryset()

    def get_categories_for_header_drop_list(self):
        model = get_models_for_count('notebook', 'smartphone')
        qs = list(self.get_queryset().annotate(*model))
        data = [
            dict(name=c.name, url=c.get_absolut_url(), count=getattr(c, self.CATEGORY_NAME_COUNT_NAME[c.name]))
            for c in qs
        ]
        return data


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Назва категорії')
    slug = models.SlugField(unique=True)
    objects = CategoryManager()

    def __str__(self):
        return self.name

    def get_absolut_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Product(models.Model):
    MIN_RESOLUTION = (400, 400)
    MAX_RESOLUTION = (4000, 4000)
    MAX_IMAGE_SIZE = 5 * 1024 * 1024  # 5 мб

    class Meta:
        abstract = True

    category = models.ForeignKey(Category, verbose_name='Категорія', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name='Назва товару')
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name='Зображення')
    description = models.TextField(verbose_name='Опис', null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Ціна')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        image = self.image
        img = Image.open(image)
        min_height, min_width = self.MIN_RESOLUTION
        max_height, max_width = self.MAX_RESOLUTION
        if img.height < min_height or img.width < min_width:
            raise MinResolutionErrorException('Розрішення зображення менше мінімального')
        if img.height > max_height or img.width > max_width:
            raise MinResolutionErrorException('Розрішення зображення більше максимально допустимого')
        # new_img = img.convert('RGB')
        # resized = new_img.resize((800, 800), Image.ANTIALIAS)
        # filestream = BytesIO()
        # resized.save(filestream, 'PNG')
        # filestream.seek(0)
        # print(self.image.name.split('.'))
        # name = '{}.{}'.format(*self.image.name.split('.'))
        # self.image = InMemoryUploadedFile(filestream, 'ImageField', name, 'png/image',
        #                                   sys.getsizeof(filestream), None)
        super().save(*args, **kwargs)


class NoteBook(Product):
    diagonal = models.CharField(max_length=255, verbose_name='Діагональ')
    display_type = models.CharField(max_length=255, verbose_name='Тип дисплею')
    processor_freq = models.CharField(max_length=255, verbose_name='Частота процесора')
    ram = models.CharField(max_length=255, verbose_name='Оперативна пам\'ять')
    video = models.CharField(max_length=255, verbose_name='Відеокарта')
    time_without_charge = models.CharField(max_length=255, verbose_name='Час роботи від акамулятора')

    def __str__(self):
        return f'{self.category.name} {self.title}'

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')


class Smartphone(Product):
    diagonal = models.CharField(max_length=255, verbose_name='Діагональ')
    display_type = models.CharField(max_length=255, verbose_name='Тип дисплею')
    resolution = models.CharField(max_length=255, verbose_name='Розрішення екрану')
    accum_volume = models.CharField(max_length=255, verbose_name='Об\'єм акамулятора')
    ram = models.CharField(max_length=255, verbose_name='Оперативна пам\'ять')
    sd = models.BooleanField(default=True, verbose_name='Наявність SD карти пам\'яті')
    sd_volume_max = models.CharField(max_length=255,
                                     null=True,
                                     blank=True,
                                     verbose_name='Максимальний об\'єм карти пам\'яті')
    main_cam_mp = models.CharField(max_length=255, verbose_name='Основна камера')
    frontal_cam_mp = models.CharField(max_length=255, verbose_name='Фронтальна камера')

    def __str__(self):
        return f'{self.category.name} : {self.title}'

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')


class CartProduct(models.Model):
    user = models.ForeignKey('Customer', verbose_name='Покупець', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_products')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True)
    object_id = models.PositiveIntegerField(null=True)
    content_object = GenericForeignKey('content_type', 'object_id')
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Загальна сума')

    def __str__(self):
        return f'Продукт: {self.content_object.title} в корзині'


class Cart(models.Model):
    owner = models.ForeignKey('Customer', verbose_name='Власник', on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Загальна сума')
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return self.id


class Customer(models.Model):
    user = models.ForeignKey(User, verbose_name='Користувач', on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, verbose_name='Номер телефона')
    address = models.CharField(max_length=255, verbose_name='Адрес')

    def __str__(self):
        return f'Покупець: {self.user.first_name} {self.user.last_name}'

shop/main_app/views.py
from django.shortcuts import render
from django.views.generic import DetailView, View

from .models import NoteBook, Smartphone, Category, LatestProducts
from .mixins import CategoryDetailMixin


class BaseView(View):

    def get(self, request, *args, **kwargs):
        categories = Category.objects.get_categories_for_header_drop_list()
        products = LatestProducts.objects.get_products_for_main_page('notebook', 'smartphone')
        context = {
            'categories': categories,
            'products': products
        }
        return render(request, 'base.html', context)


class ProductDetailView(CategoryDetailMixin, DetailView):
    CT_MODEL_MODEL_CLASS = {
        'notebook': NoteBook,
        'smartphone': Smartphone
    }

    def dispatch(self, request, *args, **kwargs):
        self.model = self.CT_MODEL_MODEL_CLASS[kwargs['ct_model']]
        self.queryset = self.model._base_manager.all()
        return super().dispatch(request, *args, **kwargs)

    context_object_name = 'product'
    template_name = 'product_detail.html'
    slug_url_kwarg = 'slug'


class CategoryDetailView(CategoryDetailMixin, DetailView):
    model = Category
    queryset = Category.objects.all()
    context_object_name = 'category'
    template_name = 'category_detail.html'
    slug_url_kwarg = 'slug'

shop/main_app/templates/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
    (function ($) {
        $('#id_sd').on('click', function (){
            if($('#id_sd').prop('checked') == true) {
                $('#id_sd_volume_max').prop('readonly', false)
                $('#id_sd_volume_max').css('background', 'white')
            } else {
                $('#id_sd_volume_max').prop('readonly', true)
                $('#id_sd_volume_max').val('')
                $('#id_sd_volume_max').css('background', 'lightgray')

            }
        })
    })(django.jQuery);
</script>
{% endblock %}

shop/main_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Shop Homepage - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico"/>
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link href="css/styles.css" rel="stylesheet"/>
</head>
<body>
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="#!">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Головна</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">Категорії</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'base' %}">Всі категорії</a></li>
                        <li>
                            <hr class="dropdown-divider"/>
                        </li>
                        {% for category in categories %}
                            <li><a class="dropdown-item" href="{{ category.url }}">{{ category.name }}
                                ({{ category.count }})</a></li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
            <form class="d-flex">
                <button class="btn btn-outline-dark" type="submit">
                    <i class="bi-cart-fill me-1"></i>
                    Корзина
                    <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                </button>
            </form>
        </div>
    </div>
</nav>
{% block content %}
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Shop in style</h1>
                <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
            </div>
        </div>
    </header>
    <!-- Section-->
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

                {% for product in products %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Sale badge-->
                            {#                            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">#}
                            {#                                Sale#}
                            {#                            </div>#}
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ product.image.url }}" alt=""/>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ product.title }}</h5>
                                    {#                                    <!-- Product reviews-->#}
                                    {#                                    <div class="d-flex justify-content-center small text-warning mb-2">#}
                                    {#                                        <div class="bi-star-fill"></div>#}
                                    {#                                        <div class="bi-star-fill"></div>#}
                                    {#                                        <div class="bi-star-fill"></div>#}
                                    {#                                        <div class="bi-star-fill"></div>#}
                                    {#                                        <div class="bi-star-fill"></div>#}
                                    {#                                    </div>#}
                                    <!-- Product price-->
                                    {{ product.price }} грн
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center">
                                    <a class="btn btn-outline-dark mt-auto" href="{{ product.get_absolut_url }}">
                                        Add to cart
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
    </section>
{% endblock %}
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2021</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"
        integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/"
        crossorigin="anonymous"></script>
<!-- Core theme JS-->
<script src="js/scripts.js"></script>
</body>
</html>

shop/main_app/templates/category_detail.html
{% extends 'base.html' %}

{% block content %}
{{ category.name }}
{% endblock %}

shop/main_app/templates/notebook_specification.html
<table class="table">
    <tbody>
    <tr>
        <td>Діагональ</td>
        <td>{{ product.diagonal }}</td>
    </tr>
    <tr>
        <td>Тип дисплею</td>
        <td>{{ product.display_type }}</td>
    </tr>
    <tr>
        <td>Частота процесора</td>
        <td>{{ product.processor_freq }}</td>
    </tr>
    <tr>
        <td>Оперативна пам'ять</td>
        <td>{{ product.ram }}</td>
    </tr>
    <tr>
        <td>Відеокарта</td>
        <td>{{ product.video }}</td>
    </tr>
    <tr>
        <td>Час роботи від акамулятора</td>
        <td>{{ product.time_without_charge }}</td>
    </tr>
    </tbody>
</table>

shop/main_app/templates/product_detail.html
{% extends 'base.html' %}
{% load specifications %}

{% block content %}
    <div class="container"></div>
    <div class="row">
        <nav aria-label="breadcrumb" class="m-3">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'base' %}">Головна</a></li>
                <li class="breadcrumb-item"><a href="#">{{ product.category.name }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ product.title }}</li>
            </ol>
        </nav>
    </div>
    <div class="row m-3">
        <div class="col-md-4">
            <img src="{{ product.image.url }}" class="img-fluid" alt="">
        </div>
        <div class="col-md-8">
            <h3>{{ product.title }}</h3>
            <p>Ціна: {{ product.price }}</p>
            <p>Опис: {{ product.description }}</p>
            <p>Характеристики: </p>

        {{ product|product_spec }}

        </div>
    </div>
{% endblock content %}

shop/main_app/templates/smartphone_specification.html
<table class="table">
    <tbody>
    <tr>
        <td>Діагональ</td>
        <td>{{ product.diagonal }}</td>
    </tr>
    <tr>
        <td>Тип дисплею</td>
        <td>{{ product.display_type }}</td>
    </tr>
    <tr>
        <td>Розрішення екрану</td>
        <td>{{ product.resolution }}</td>
    </tr>
    <tr>
        <td>Об'єм акамулятора</td>
        <td>{{ product.accum_volume }}</td>
    </tr>
    <tr>
        <td>Оперативна пам'ять</td>
        <td>{{ product.ram }}</td>
    </tr>
    <tr>
        <td>Наявність роз'єму для SD карти памяті</td>
        <td>{{ product.sd }}</td>
    </tr>
    <tr>
        <td>Максимальний об'єм встроїної пам'яті</td>
        <td>{{ product.sd_volume_max }}</td>
    </tr>
    <tr>
        <td>Основна камера</td>
        <td>{{ product.main_cam_mp }}</td>
    </tr>
    <tr>
        <td>Фронтальна камера</td>
        <td>{{ product.frontal_cam_mp }}</td>
    </tr>
    </tbody>
</table>